### ISSUE TITLE
UUID primary keys

### ISSUE THREAD

**Issue by mattbeedle** [fredwu/datamappify#13]
Using Postgres UUID primary keys isn't supported right now.

``` ruby
create_table :users, id: false do |t|
  t.primary_key :id, :uuid
end


UserRepository.find("4224109b-a9c8-4d8b-9f0b-f2a8f2a73174")

NoMethodError: undefined method `keys' for "4224109b-a9c8-4d8b-9f0b-f2a8f2a73174":String
        from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.2/lib/datamappify/data/criteria/relational/find_multiple.rb:35:in `updated_attributes'
        from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.2/lib/datamappify/data/criteria/relational/find_multiple.rb:16:in `initialize'
        from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.2/lib/datamappify/data/provider/common_provider.rb:94:in `new'
        from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.2/lib/datamappify/data/provider/common_provider.rb:94:in `build_criteria'
        from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.2/lib/datamappify/repository/query_method/method.rb:64:in `dispatch_criteria_to_default_source'
        from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.2/lib/datamappify/repository/query_method/find_multiple.rb:16:in `perform'
        from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.2/lib/datamappify/repository/query_methods.rb:31:in `find'
        from (irb):2
        from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands/console.rb:90:in `start'
        from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands/console.rb:9:in `start'
        from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands.rb:64:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

I'm a bit busy at the moment, but I'll try to get a pull request sorted out for this as soon as I have the time, unless someone else gets there first.

**Comment by fredwu** [comment]
Solved in #14.
