### ISSUE TITLE
NoMethodError: undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by mattbeedle** [fredwu/datamappify#7]
Is this a bug, or did I configure something wrong?

Entity

``` ruby
class Deployment
  include Datamappify::Entity

  attribute :user_id,         Integer
  attribute :branch_name,     String
  attribute :revision,        String
  attribute :heroku_app_name, String

  validates :user_id, :heroku_app_name, :branch_name, presence: true
end
```

Repository

``` ruby
class DeploymentRepository
  include Datamappify::Repository

  for_entity Deployment

  default_provider :ActiveRecord

  # Not sure what model to map this onto yet
  map_attribute :user_id,         'DeploymentData#user_id'
  map_attribute :branch_name,     'DeploymentData#branch_name'
  map_attribute :repository,      'DeploymentData#repository'
  map_attribute :heroku_app_name, 'DeploymentData#heroku_app_name'

  after_create :deploy!

  private

  def deploy!
    # Do some deployment stuff here...
  end
end
```

Model

``` ruby
class DeploymentData < ActiveRecord::Base
end
```

Error

``` ruby
2.0.0p247 :001 > d = Deployment.new(branch_name: 'test', heroku_app_name: 'my-test-app', user_id: 1)
 => #<Deployment> 
2.0.0p247 :002 > DeploymentRepository.save(d)
   (0.1ms)  BEGIN
   (0.1ms)  ROLLBACK
NoMethodError: undefined method `split' for nil:NilClass
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/data/mapper/attribute.rb:156:in `parse_source'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/data/mapper/attribute.rb:46:in `initialize'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/data/mapper.rb:100:in `new'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/data/mapper.rb:100:in `map_custom_attribute'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/data/mapper.rb:88:in `block in custom_attributes'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/data/mapper.rb:87:in `each'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/data/mapper.rb:87:in `collect'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/data/mapper.rb:87:in `custom_attributes'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/data/mapper.rb:73:in `custom_attribute_names'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/data/mapper.rb:67:in `default_attribute_names'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/data/mapper.rb:80:in `default_attributes'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/data/mapper.rb:49:in `attributes'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/data/mapper.rb:55:in `classified_attributes'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/repository/query_method/method.rb:110:in `block in attributes_walker'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
... 9 levels...
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/repository/query_method/save.rb:36:in `create_or_update'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/repository/query_method/save.rb:8:in `block in perform'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/repository/unit_of_work/persistent_states.rb:47:in `call'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/repository/unit_of_work/persistent_states.rb:47:in `update'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/repository/query_method/save.rb:7:in `perform'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/repository/query_methods.rb:48:in `block in create'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/repository/query_method/callbacks.rb:29:in `call'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/repository/query_method/callbacks.rb:29:in `run_callbacks'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/repository/query_methods.rb:47:in `create'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/datamappify-0.53.1/lib/datamappify/repository/query_methods.rb:85:in `save'
    from (irb):2
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands/console.rb:90:in `start'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands/console.rb:9:in `start'
    from /Users/hansolo/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands.rb:64:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'2.0.0p247 :003 > 
```

**Comment by mattbeedle** [comment]
Ups, don't worry, just realised I was missing ActiveRecord:: prefix in the repository!
